### ISSUE TITLE
game-stats issues

### ISSUE THREAD

**Issue by connorhsm** [twohoursonelife/dictator#70]
Message in game-stats channel has been consistently incorrect, seemingly getting stuck at some point and not updating again until the bot is restarted. ~~Today I found it as if the entire text of the message had been edited out.~~ Adk had actually just deleted the message as it contained incorrect information due to this bug.

This feature has always thrown some kind of error which I think relates back to the discord.py library. I have enabled logging of the Screen session the bot is running in and am now waiting to grab the error from the log.

**Comment by connorhsm** [comment]
Potentially fixed https://github.com/twohoursonelife/dictator/commit/31ad4cc6234669fa4d24e44183cffa4feccdff1b

**Comment by connorhsm** [comment]
Not fixed by above.
Error:
```Unhandled exception in internal background task 'stats_loop'.
Traceback (most recent call last):
  File "/home/thol/.cache/pypoetry/virtualenvs/dictator-pjPTBC3y-py3.8/lib/python3.8/site-packages/discord/ext/tasks/__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "/home/thol/dictator/dictator/cogs/stats.py", line 33, in stats_loop
    await self.update_stats()
  File "/home/thol/dictator/dictator/cogs/stats.py", line 40, in update_stats
    await self.stats_msg.edit(embed=embed)
  File "/home/thol/.cache/pypoetry/virtualenvs/dictator-pjPTBC3y-py3.8/lib/python3.8/site-packages/discord/message.py", line 1111, in edit
    data = await self._state.http.edit_message(self.channel.id, self.id, **fields)
  File "/home/thol/.cache/pypoetry/virtualenvs/dictator-pjPTBC3y-py3.8/lib/python3.8/site-packages/discord/http.py", line 252, in request
    raise DiscordServerError(r, data)
discord.errors.DiscordServerError: 503 Service Unavailable (error code: 0): upstream connect error or disconnect/reset before headers. reset reason: connection failure```

**Comment by connorhsm** [comment]
Issue appears to no longer occur.

**Comment by connorhsm** [comment]
Issue continues, I've resorted to restarting the bot daily using Watchtower.
