### ISSUE TITLE
Exception when attempting to delete a message in a DM channel

### ISSUE THREAD

**Issue by connorhsm** [twohoursonelife/dictator#71]
```
Successfully created an account for PIEROGI!#3286 using the username PIEROGI-3286.
Successfully created an account for Si_and_Sp#4232 using the username SiandSp-4232.
We tried to create an account for kya#4466 but they already had one, so we'll send them their login information.
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/thol/.cache/pypoetry/virtualenvs/dictator-pjPTBC3y-py3.8/lib/python3.8/site-packages/discord/client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "/home/thol/dictator/dictator/cogs/informational.py", line 20, in on_message
    await message.delete()
  File "/home/thol/.cache/pypoetry/virtualenvs/dictator-pjPTBC3y-py3.8/lib/python3.8/site-packages/discord/message.py", line 803, in delete
    await self._state.http.delete_message(self.channel.id, self.id)
  File "/home/thol/.cache/pypoetry/virtualenvs/dictator-pjPTBC3y-py3.8/lib/python3.8/site-packages/discord/http.py", line 241, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50003): Cannot execute action on a DM channel
Successfully created an account for Jlmanning615#0753 using the username Jlmanning615-0753.
Successfully created an account for Ryuta#1939 using the username Ryuta-1939.
```

Appears to be caused by attempting to delete a message in a DM channel.

**Comment by TanyaPegasus** [comment]
Is this one still relevant now that a lot of those messages are sent within the server as ephemeral messages? 
I'm seeing if there's anything in the issues that I can take a look at. I found a little on this topic, but I'm nor sure if there's still any messages that you would want to be able to delete. If you still have a use for this, I'll research further.

**Comment by connorhsm** [comment]
I'll close this for now as it has not been a problem.
